name: Test
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v2.0.2

      - name: Nim - TS
        run: deno test
